### PR TITLE
Add incoming mail support in Docker

### PR DESCRIPTION
**Pull request by naglis**
Hello all,

as per [comment](https://community.openproject.com/topics/6650) by @crohr this PR adds a section in supervisor.conf to enable incoming email support inside OpenProject Docker container. Please let me know if I made the PR against the wrong branch.

I had an issue with quoting when passing the [`IMAP_*` environment variables](https://github.com/opf/openproject-ce/blob/stable/6/docker/cron) to Docker -- when passing the `IMAP_HOST`, `IMAP_USERNAME` or `IMAP_PASSWORD` quoted in single or double-quotes, the values would somehow be passed incorrectly to the _cron_ script. Not sure why, maybe I was doing something wrong. Nonetheless, it works if the values are unquoted, so a sample Docker environment file could look like:

``` bash
...
# IMAP (Incoming email)
IMAP_ENABLED=true
IMAP_SSL=true
IMAP_PORT=993
IMAP_CHECK_INTERVAL=300
IMAP_HOST=imap.example.com
IMAP_USERNAME=no-reply@example.com
IMAP_PASSWORD=secret
...
```

Regarding the CLA -- I have filled out, scanned and signed the CLA, however, when I sent it to cla@openproject.org, I have received a notice from Google mail daemon saying that the delivery failed. I have tried twice. Could somebody check this issue?

### CODE REVIEW

**Comment by lindenthal** [comment]
Hi Naglis,

Thanks for your PR. Cyril will have a look at this when he is back from holiday.

Regarding the CLA: The email adress got lots. I just recreated it. Now it works again. Thanks for the feeback.

Best 
Niels

**Comment by crohr** [comment]
@naglis regarding the double quotes, if you used an env file with docker (via `--env-file`), then you need to remove all quotes since docker will pass the value of your variables as is (see https://github.com/docker/docker/issues/26053 for reference).

I'm looking at the PR today and merging it asap, thanks!

**Comment by naglis** [comment]
>  if you used an env file with docker (via --env-file), then you need to remove all quotes since docker will pass the value of your variables as is (see docker/docker#26053 for reference).

Good to know, thanks!

**Comment by naglis** [comment]
@crohr, it seems that the changes from this PR [did not make it into version 7](https://github.com/opf/openproject-ce/blob/stable/7/docker/supervisord.conf). Could you take a look?

**Pull request merged**
